engines:
  # ... CONFIG CONTENT ...
  phpmd:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      Controversial/Superglobals:
        enabled: false
      Generic Files LineLength TooLong:
        enabled: false
      Squiz WhiteSpace SuperfluousWhitespace EndLine:
        enabled: false
# ... CONFIG CONTENT ...
